### PR TITLE
[WIP] Try pass vectorbt data to Agent

### PR DESCRIPTION
**Pull request by dev590t**
This PR contains a tutorial to try to pass vectorbt data to the agent

### CODE REVIEW

**Comment by dev590t** [comment]
I need some help. I'm blocked on a error.

In the notebook file, I get this error:
```
trained_a2c = agent.train_model(model=model_a2c, 
                             tb_log_name='a2c',
                             total_timesteps=50000)
# ValueError: cannot convert float NaN to integer
```

But the training data doesn't contain any NaN:
```
processed_full.isnull().sum().sum()
# return 0
```

Where is from the NaN value?

**Comment by dev590t** [comment]
..The code doesn't still run totally. It is still work in progress. I have open the PR because I want some help to finish it, but I doesn't expect merge it immediately.

**Comment by ZiyiXia** [comment]
Sorry for merging it in hurry. Would you like to submit an issue about the problem mentioned above? Thanks for your effort and contribution!

**Comment by dev590t** [comment]
Ok, I open it

**Pull request merged**
