### PR TITLE
* Enforce black formatting

### PR DESCRIPTION
**Pull request by hoeckxer**
* Enforce black formatting
* Run pytest on push on default branch & pull request

### CODE REVIEW

**Comment by zhumingpassional** [comment]
we will check it. thanks.

**Comment by zhumingpassional** [comment]
good. thanks.

**Comment by eyast** [comment]
Test.yml content a special function to download TA lib and I'm not sure right now if the new test methodology performs this download or not on Linux. can you please confirm ? Thanks

**Comment by eyast** [comment]
I sent the previous consent to quick And forgot to say thank you for the great work.

**Pull request merged**
