### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by eyast**
I have added several tests:
- Added testcase for Binance
- Added testcase for clean_data()
- added testcase for add_technical_indicator(both stockstats and TALib)

### CODE REVIEW

**Comment by eyast** [comment]
Hi @zhumingpassional  - let me know if you have any questions before merging this PR, thanks

**Comment by eyast** [comment]
Hi @Athe-kunal - this is the PR that I've mentioned. Please check out the result of the first test case (the one above pre-commit.ci). Once it completes, it should fail, with some failures related to get_data() and get_trading_days(). can you help create issues in the project tracker so we start resolving those? Thanks!!

**Comment by zhumingpassional** [comment]
@eyast 
in test_yahoo.py, i am wondering the reason of building a class not a function just like test_baostock, which includes access data, clean data, and add technical indicators?

**Comment by eyast** [comment]
The real difference is that the Yahoo test cases are built on top of pytest - a testing framework. Test_baostock is not built on top of a testing framework. We need a testing framework. Class or not class is not very relevant - both work
________________________________

**Comment by eyast** [comment]
So you want to setup some time and discuss ? I don't see the premise of having less test files or just one class. I don't mind, but I don't think we should rework

**Pull request merged**
