### PR TITLE
Create fx_training.py

### PR DESCRIPTION
**Pull request by mhdmyz**

### CODE REVIEW

**Comment by zhumingpassional** [comment]
Good. 

I have a suggestion: this PR only adds fx_training, pls do no change other files. That is, only one file (fx_training) should be changed.

**Comment by zhumingpassional** [comment]
In https://github.com/AI4Finance-Foundation/FinRL-Meta/pull/218/files, I can see that you changed totally 3 files. 

image
image
image

**Comment by zhumingpassional** [comment]
It may cost reviewers to read and check if you changed them.  could you pls not change other files, even deleting and entering few lines of space?

**Comment by XiaoYangLiu-FinRL** [comment]
> Sure! But it was just for organizing and improving the readability of codes!

It is understandable.   No worry.
It is just more professional that "keep each commit to minimum change, with a self-contained functionality".

Also, you are welcome to submit a PR to organize the codes, if you see fit.

**Comment by XiaoYangLiu-FinRL** [comment]
> Who's supposed to merge these pull requests into master?

Currently, the team is using this rule "Each change of should be a PR, and each PR should have someone to test before merging."  

I just add the available members to "Assignees", you can interact with any one of them.
When you become more familiar with the projects, I can grant you higher access to review PRs.  Thanks.

**Pull request merged**
